from collections.abc import MutableSequence
from typing import Generator

class Header:
    def __init__(self, name: bytes, value: bytes):
        self.name = name
        self.value = value

    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[bytes, None, None]: ...
    def __eq__(self, other: object) -> bool: ...

HeaderType = tuple[bytes, bytes]

class Headers:
    def __init__(self, values: list[HeaderType] | None = None):
        self.values = values

    def get(self, name: bytes) -> tuple[bytes]: ...
    def get_tuples(self, name: bytes) -> list[HeaderType]: ...
    def get_first(self, key: bytes) -> bytes | None: ...
    def get_single(self, key: bytes) -> bytes: ...
    def merge(self, values: list[HeaderType]) -> None: ...
    def update(self, values: dict[bytes, bytes]) -> None: ...
    def items(self) -> Generator[HeaderType, None, None]: ...
    def clone(self) -> "Headers": ...
    def add_many(
        self, values: dict[bytes, bytes] | list[tuple[bytes, bytes]]
    ) -> None: ...
    def __add__(self, other: "Headers" | Header | HeaderType | MutableSequence) -> "Headers": ...
    def __radd__(self, other: "Headers" | Header | HeaderType | MutableSequence) -> "Headers": ...
    def __iadd__(self, other: "Headers" | Header | HeaderType | MutableSequence) -> "Headers": ...
    def __iter__(self) -> Generator[HeaderType, None, None]: ...
    def __setitem__(self, key: bytes, value: bytes) -> None: ...
    def __getitem__(self, item: bytes) -> tuple[bytes]: ...
    def keys(self) -> tuple[bytes, ...]: ...
    def add(self, name: bytes, value: bytes) -> None: ...
    def set(self, name: bytes, value: bytes) -> None: ...
    def remove(self, key: bytes) -> None: ...
    def contains(self, key: bytes) -> bool: ...
    def __delitem__(self, key: bytes) -> None: ...
    def __contains__(self, key: bytes) -> bool: ...
    def __repr__(self) -> str: ...
