from typing import Any, Optional, Union

class InvalidURL(Exception):
    def __init__(self, message: str) -> None: ...

class URL:
    value: bytes
    schema: bytes | None
    host: bytes | None
    port: int
    path: bytes
    query: bytes
    fragment: bytes | None
    is_absolute: Any
    def __init__(self, value: bytes) -> None: ...
    def join(self, other: "URL") -> "URL": ...
    def base_url(self) -> "URL": ...
    def with_host(self, host: bytes) -> "URL": ...
    def with_scheme(self, scheme: bytes) -> "URL": ...
    def with_query(self, query: bytes) -> "URL": ...
    def __add__(self, other: bytes | "URL") -> "URL": ...
    def __eq__(self, other: object) -> bool: ...

def join_prefix(prefix: str, path: str) -> str:
    """Combines a prefix and a path, ensuring a single slash between them."""
